server:
    port: 8300

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/
spring:
    application:
        name: consumer
feign:
    hystrix:
        enabled: true