server:
    port: 8000

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/
spring:
    application:
        name: zuul
zuul:
    ignored-services: eureka